version: '3'
services:
  mysql:
    image: cognito/mysql:5.6
    build: ./docker/mysql
    ports:
      - 3306:3306
    volumes:
      - "./tmp/docker/data/mysql/var/lib/mysql:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: cognito_sample_development
      MYSQL_USER: cognito_sample
      MYSQL_PASSWORD: password
